### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by Billy1900** [zhouchunpong/GCN_Keras#9]
tf version: 1.14.0
```
Train on 2708 samples, validate on 2708 samples
Epoch 1/200
Traceback (most recent call last):
  File "D:\JetBrains\Toolbox\apps\PyCharm-P\ch-0\201.6668.115\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\JetBrains\Toolbox\apps\PyCharm-P\ch-0\201.6668.115\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/PC/Desktop/GCN_Keras-master/train.py", line 85, in <module>
    callbacks=[es_callback])
  File "D:\python37\lib\site-packages\keras\engine\training.py", line 1239, in fit
    validation_freq=validation_freq)
  File "D:\python37\lib\site-packages\keras\engine\training_arrays.py", line 196, in fit_loop
    outs = fit_function(ins_batch)
  File "D:\python37\lib\site-packages\tensorflow\python\keras\backend.py", line 3277, in __call__
    dtype=tensor_type.as_numpy_dtype))
  File "D:\python37\lib\site-packages\numpy\core\_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

How to solve it?

**Comment by zhouchunpong** [comment]
Please check the other environment in file ‘requirement.txt’.
And my Python version is 3.63
